name: Build

env:
  REGISTRY_IMAGE: milespoupart/homebox

on:
  pull_request:
  workflow_dispatch:
  push:
    tags:
      - "v*"

jobs:
  build-web:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Print env
        run: |
          corepack enable
          echo "node version:" $(node -v)
          echo "npm version:" $(npm -v)
          echo "pnpm version:" $(pnpm -v)
      - name: Bootstrap
        run: |
          make bootstrap-web
      - name: Build frontend assets
        run: |
          make build-web
      - name: Upload
        uses: actions/upload-artifact@v4
        with:
          name: web
          path: build/static

  build-binary:
    name: build-${{ matrix.platform.file }}
    runs-on: ${{ matrix.platform.runner }}
    needs: build-web
    strategy:
      fail-fast: false
      matrix:
        platform:
          - runner: macos-latest
            target: aarch64-apple-darwin
            file: darwin-arm64
          - runner: macos-latest
            target: x86_64-apple-darwin
            file: darwin-amd64
          - runner: windows-latest
            target: x86_64-pc-windows-msvc
            file: windows-amd64.exe
          - runner: windows-latest
            target: i686-pc-windows-msvc
            file: windows-386.exe
          - runner: ubuntu-latest
            target: x86_64-unknown-linux-gnu
            file: linux-amd64
          - runner: ubuntu-latest
            target: x86_64-unknown-linux-musl
            file: linux-amd64-musl
            tool: musl-tools clang llvm
          # TODO: ohos is not ready
          # - runner: ubuntu-latest
          #   target: aarch64-unknown-linux-ohos
          #   file: linux-ohos
          - runner: ubuntu-latest
            target: aarch64-unknown-linux-gnu
            file: linux-arm64
            tool: gcc-aarch64-linux-gnu binutils-aarch64-linux-gnu
          - runner: ubuntu-latest
            target: aarch64-unknown-linux-musl
            file: linux-arm64-musl
            tool: musl-tools clang llvm gcc-multilib
          - runner: ubuntu-latest
            target: armv7-unknown-linux-gnueabihf
            file: linux-armv7
            tool: gcc-arm-linux-gnueabihf binutils-arm-linux-gnueabihf
          - runner: ubuntu-latest
            target: armv7-unknown-linux-musleabihf
            file: linux-armv7-musl
            tool: musl-tools clang llvm gcc-multilib
          - runner: ubuntu-latest
            target: i686-unknown-linux-gnu
            file: linux-386
            tool: gcc-multilib
          - runner: ubuntu-latest
            target: i686-unknown-linux-musl
            file: linux-386-musl
            tool: musl-tools clang llvm gcc-multilib
    env:
      CARGO_TARGET_AARCH64_UNKNOWN_LINUX_GNU_LINKER: aarch64-linux-gnu-gcc
      CARGO_TARGET_ARMV7_UNKNOWN_LINUX_GNUEABIHF_LINKER: arm-linux-gnueabihf-gcc
      # musl targets configuration
      CC_x86_64_unknown_linux_musl: clang
      AR_x86_64_unknown_linux_musl: llvm-ar
      CARGO_TARGET_X86_64_UNKNOWN_LINUX_MUSL_RUSTFLAGS: "-Clink-self-contained=yes -Clinker=rust-lld"
      CC_aarch64_unknown_linux_musl: clang
      AR_aarch64_unknown_linux_musl: llvm-ar
      CARGO_TARGET_AARCH64_UNKNOWN_LINUX_MUSL_RUSTFLAGS: "-Clink-self-contained=yes -Clinker=rust-lld"
      CC_armv7_unknown_linux_musleabihf: clang
      AR_armv7_unknown_linux_musleabihf: llvm-ar
      CARGO_TARGET_ARMV7_UNKNOWN_LINUX_MUSLEABIHF_RUSTFLAGS: "-Clink-self-contained=yes -Clinker=rust-lld"
      CC_i686_unknown_linux_musl: clang
      AR_i686_unknown_linux_musl: llvm-ar
      CARGO_TARGET_I686_UNKNOWN_LINUX_MUSL_RUSTFLAGS: "-Clink-self-contained=yes -Clinker=rust-lld"
    steps:
      - uses: actions/checkout@v4
      - name: Print env
        run: |
          echo "rustc version:" $(rustc --version)
          echo "cargo version:" $(cargo --version)
          echo "rustup version:" $(rustup --version)
      - name: Download Static files
        uses: actions/download-artifact@v4
        with:
          name: web
          path: build/static
      - name: Install tool
        if: matrix.platform.tool
        run: sudo apt-get install ${{ matrix.platform.tool }}
      - name: Bootstrap
        run: |
          make bootstrap-server
      - name: Build
        run: make build-arch TARGET=${{ matrix.platform.target }} FILE=${{ matrix.platform.file }}
      - name: Upload
        uses: actions/upload-artifact@v4
        with:
          name: homebox-${{ matrix.platform.file }}
          path: build/arch

  release-tag:
    runs-on: ubuntu-latest
    needs: build-binary
    if: github.event_name == 'push' && startsWith(github.ref, 'refs/tags/v')
    steps:
      - uses: actions/checkout@v4
      - name: Download binary
        uses: actions/download-artifact@v4
        with:
          pattern: homebox-*
          path: build/arch
          merge-multiple: true
      - name: Upload to Release
        run: |
          make pack-arch TAG=${{ github.ref }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}